Models/ErrorViewModel.cs
using System;

namespace MultiLingual.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Flags.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MultiLingual.Models
{
    public class Flags
    {
        public int Id { get; set; }
        public string Sname { get; set; }
        
    }
}

Controllers/FlagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MultiLingual.Models;

namespace MultiLingual.Controllers
{
    public class FlagController : Controller
    {
        private readonly Microsoft.Extensions.Localization.IStringLocalizer<FlagController> _localizer;
        public FlagController(Microsoft.Extensions.Localization.IStringLocalizer<FlagController> localizer)
        {
            _localizer = localizer;
        }
       
        public IActionResult Entertainment()
        {
        ViewBag.Message = "This is the list of latest great songs:-";
            var flags = new List<Flags>()
            {
                 new Flags{Sname = _localizer["Dont Let me down"]},
                 new Flags{Sname = _localizer["Lagdi Lahore Di"]},
                 new Flags{Sname = _localizer["On my way"]}

            };
            return View(flags);
        }
        public IActionResult Entertainment2()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MultiLingual.Models;

namespace MultiLingual.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Flag/Entertainment.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model List<Flags>
@{
    ViewData["Title"] = "Entertainment2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    

<h1>@Localizer["mess"]</h1>

<ul>
    @foreach (var songs in Model)
    {   
        
        <li>@songs.Sname</li>
    }
</ul>

<ul class="pagination">
      <li class="active"><a href="#">1</a></li>
      <li ><a asp-area="" asp-controller="Flag" asp-action="Entertainment2">2</a></li>
</ul>

Views/Flag/Entertainment2.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Entertainment2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Localizer["List of movies:-"]</h1>
<ol>
    <li>@Localizer["Avengers"]</li>
    <li>@Localizer["The Imitation Game"]</li>
    <li>@Localizer["Ford vs Ferrari"]</li>
</ol>

 <ul class="pagination">
        <li ><a asp-area="" asp-controller="Flag" asp-action="Entertainment">1</a></li>
        <li class="active"><a asp-area="" asp-controller="Flag" asp-action="Entertainment2">2</a></li>
 </ul>

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">@Localizer["Welcome to the entertainment store!"]</h1>

</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MultiLingual</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MultiLingual</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flag" asp-action="Entertainment">@Localizer["Entertainment"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" href="?culture=en-US">ENGLISH</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" href="?culture=de-DE">GERMAN</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MultiLingual - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>